Create ar.lua
qbcore-framework/qb-weathersync pull request #41
Opened 2022-01-23 15:13 UTC by elvodkaa

2022-01-30 04:34 UTC, MonkeyWhisper requested changes
Please translate

2022-01-30 04:34 UTC, MonkeyWhisper commented on locales/ar.lua
> +        availableweather = 'extrasunny, clear, neutral, smog, foggy, overcast, clouds, clearing, rain, thunder, snow, blizzard, snowlight, xmas, halloween',
We need these translated.

2022-01-30 04:34 UTC, MonkeyWhisper commented on locales/ar.lua
> +        invalid = 'يوجد \nEXTRASUNNY CLEAR NEUTRAL SMOG FOGGY OVERCAST CLOUDS CLEARING RAIN THUNDER SNOW BLIZZARD SNOWLIGHT XMAS HALLOWEEN ',
Translate please

2022-02-02 11:43 UTC, elvodkaa commented
Bro i cant bcz this is for commands so

2022-02-24 22:40 UTC, closed without merging