Realworld Weather Sync
qbcore-framework/qb-weathersync pull request #67
Opened 2022-11-25 12:51 UTC by BrianxTu

**Describe Pull request**
This adds support for real-world weather. Using weather.gov's api, and lat/long to perform 2 http requests to get the base information needed.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **[yes]**
- Does your code fit the style guidelines? **[yes]**
- Does your PR fit the contribution guidelines? **[yes]**

2022-11-26 15:05 UTC, AnishBplayz commented
Will it sync server side or client side ?

2022-12-05 20:54 UTC, CptNoHand commented
Time sync would be nice aswell.

2022-12-08 13:11 UTC, Z3rio requested changes
This should fix your linting :)

2022-12-08 13:11 UTC, Z3rio commented on server/server.lua
> +            local temp = json.decode(rText)
```suggestion
        PerformHttpRequest(setupLink, function(err, rText)
            if err and err ~= 0 then
                print("Error code: " .. err)
            end
            local temp = json.decode(rText)
```
Fix linting issue

2022-12-08 13:11 UTC, Z3rio commented on server/server.lua
> +                local temp2 = json.decode(rText2)
```suggestion
            PerformHttpRequest(temp["properties"]["forecastHourly"], function(err2, rText2)
                local temp2 = json.decode(rText2)
                if err2 and err2 ~= 0 then
                    print("Error code: " .. err2)
                end
```
Fix linting

2022-12-22 14:30 UTC, BrianxTu reviewed
The changes made are all good with me. Thanks for your time.

2023-01-04 19:35 UTC, iktray approved these changes

2023-10-02 15:45 UTC, closed without merging